"""
Build docs/presentation.pptx from the project's real results.

Slides carry concise bullets; the detailed What / Why / How narrative goes into the
speaker notes so the deck is presentable as-is. All figures embedded come from
plots/ (generated by the analysis scripts); all numbers match docs/presentation.md.

Run:  ./venv/bin/python scripts/build_pptx.py
"""

import glob
import os

from pptx import Presentation
from pptx.util import Inches, Pt
from pptx.dml.color import RGBColor
from pptx.enum.text import PP_ALIGN

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PLOTS = os.path.join(ROOT, "plots")
OUT = os.path.join(ROOT, "docs", "presentation.pptx")

NAVY = RGBColor(0x1F, 0x3A, 0x5F)
ACCENT = RGBColor(0x2C, 0xA0, 0x2C)
GRAY = RGBColor(0x55, 0x55, 0x55)

prs = Presentation()
prs.slide_width = Inches(13.333)   # 16:9
prs.slide_height = Inches(7.5)
SW, SH = prs.slide_width, prs.slide_height
BLANK = prs.slide_layouts[6]


def _tb(slide, left, top, width, height):
    box = slide.shapes.add_textbox(left, top, width, height)
    tf = box.text_frame
    tf.word_wrap = True
    return tf


def _set(p, text, size, bold=False, color=None, align=None, space=4):
    p.text = text
    p.font.size = Pt(size)
    p.font.bold = bold
    if color is not None:
        p.font.color.rgb = color
    if align is not None:
        p.alignment = align
    p.space_after = Pt(space)


def title_slide(title, subtitle, footer):
    s = prs.slides.add_slide(BLANK)
    bar = s.shapes.add_shape(1, 0, Inches(2.5), SW, Inches(1.7))
    bar.fill.solid()
    bar.fill.fore_color.rgb = NAVY
    bar.line.fill.background()
    tf = bar.text_frame
    tf.word_wrap = True
    _set(tf.paragraphs[0], title, 36, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF),
         align=PP_ALIGN.CENTER)
    tf2 = _tb(s, Inches(1), Inches(4.4), Inches(11.3), Inches(1.2))
    _set(tf2.paragraphs[0], subtitle, 20, color=GRAY, align=PP_ALIGN.CENTER)
    tf3 = _tb(s, Inches(1), Inches(6.6), Inches(11.3), Inches(0.6))
    _set(tf3.paragraphs[0], footer, 14, color=GRAY, align=PP_ALIGN.CENTER)
    return s


def section_slide(kicker, title):
    s = prs.slides.add_slide(BLANK)
    band = s.shapes.add_shape(1, 0, Inches(2.7), SW, Inches(2.1))
    band.fill.solid()
    band.fill.fore_color.rgb = NAVY
    band.line.fill.background()
    tf = band.text_frame
    tf.word_wrap = True
    _set(tf.paragraphs[0], kicker, 18, bold=True,
         color=RGBColor(0x9F, 0xC5, 0xE8), align=PP_ALIGN.CENTER)
    p = tf.add_paragraph()
    _set(p, title, 34, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF),
         align=PP_ALIGN.CENTER)
    return s


def _header(s, title):
    band = s.shapes.add_shape(1, 0, 0, SW, Inches(0.9))
    band.fill.solid()
    band.fill.fore_color.rgb = NAVY
    band.line.fill.background()
    tf = band.text_frame
    tf.word_wrap = True
    tf.margin_left = Inches(0.4)
    _set(tf.paragraphs[0], title, 24, bold=True, color=RGBColor(0xFF, 0xFF, 0xFF))


def _bullets(tf, bullets):
    """bullets: list of (text, level, bold) tuples."""
    for i, (text, level, bold) in enumerate(bullets):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        size = 18 if level == 0 else 15
        prefix = "" if level == 0 else "   "
        marker = "•  " if level == 0 else "–  "
        _set(p, f"{prefix}{marker}{text}", size, bold=bold,
             color=NAVY if bold and level == 0 else (GRAY if level else None),
             space=5)
        p.level = level


def content_slide(title, bullets, notes=""):
    s = prs.slides.add_slide(BLANK)
    _header(s, title)
    tf = _tb(s, Inches(0.6), Inches(1.1), Inches(12.1), Inches(6.1))
    _bullets(tf, bullets)
    if notes:
        s.notes_slide.notes_text_frame.text = notes
    return s


def _find_plot(image):
    """Locate a plot by filename. Plots now live in plots/approachN/ subfolders,
    so fall back to a recursive search if it is not at the plots/ top level."""
    top = os.path.join(PLOTS, image)
    if os.path.exists(top):
        return top
    for hit in glob.glob(os.path.join(PLOTS, "**", image), recursive=True):
        return hit
    return None


def figure_slide(title, image, bullets, notes=""):
    s = prs.slides.add_slide(BLANK)
    _header(s, title)
    img = _find_plot(image)
    if img:
        s.shapes.add_picture(img, Inches(0.5), Inches(1.2), height=Inches(5.6))
    tf = _tb(s, Inches(7.4), Inches(1.2), Inches(5.5), Inches(5.9))
    _bullets(tf, bullets)
    if notes:
        s.notes_slide.notes_text_frame.text = notes
    return s


def table_slide(title, headers, rows, notes="", col_widths=None, fs=12):
    s = prs.slides.add_slide(BLANK)
    _header(s, title)
    nrows, ncols = len(rows) + 1, len(headers)
    gt = s.shapes.add_table(nrows, ncols, Inches(0.5), Inches(1.2),
                            Inches(12.3), Inches(0.4 * nrows)).table
    if col_widths:
        for c, w in enumerate(col_widths):
            gt.columns[c].width = Inches(w)
    for c, h in enumerate(headers):
        cell = gt.cell(0, c)
        cell.text = h
        para = cell.text_frame.paragraphs[0]
        para.font.size = Pt(fs)
        para.font.bold = True
        para.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)
        cell.fill.solid()
        cell.fill.fore_color.rgb = NAVY
    for r, row in enumerate(rows, start=1):
        for c, val in enumerate(row):
            cell = gt.cell(r, c)
            cell.text = str(val)
            para = cell.text_frame.paragraphs[0]
            para.font.size = Pt(fs)
            if c == 0:
                para.font.bold = True
    if notes:
        s.notes_slide.notes_text_frame.text = notes
    return s


# --------------------------------------------------------------------------- #
# Build the deck
# --------------------------------------------------------------------------- #

title_slide(
    "LLMs for Ranking-based Solubility Optimization",
    "Using an LLM to find the most water-soluble molecule under a 15-evaluation budget",
    "Anand Karna  |  MA-INF 4245, Lab AI for Scientific Discovery, University of Bonn",
)

# ---- Introduction -------------------------------------------------------- #
content_slide(
    "Introduction: the problem and the setup",
    [
        ("Goal: find the molecule with highest aqueous solubility (LogS) using an LLM, "
         "budget = 15 evaluations per run", 0, True),
        ("Oracle: ESOL (Delaney) computes LogS from structure. Cheap, R^2 ~0.69, an "
         "estimator not truth", 0, False),
        ("Dataset: AqSolDB (9,982 molecules). Source of seeds, pools, random baseline. "
         "NOT the simulator", 0, False),
        ("13 fixed seed molecules give the LLM its only context. Bar to beat = methanol "
         "+0.208", 0, False),
        ("No API budget: every prompt copy-pasted by hand into ChatGPT / Claude / "
         "DeepSeek / Gemini", 0, False),
        ("Three approaches, each asking LESS of the LLM:", 0, True),
        ("A1 Direct Optimizer: the LLM invents molecules", 1, False),
        ("A2 BO + Regressor: the LLM predicts a number + confidence", 1, False),
        ("A3 Preferential BO: the LLM only judges duels, A vs B", 1, False),
    ],
    notes=(
        "WHAT: optimize LogS with an LLM under a 15-eval budget. The LLM is the brain; "
        "ESOL is the oracle.\n"
        "WHY runs: an LLM is stochastic, one run could be a fluke. WHY 2 runs: the "
        "minimum that shows reproducibility vs path-dependence while staying affordable "
        "under hand-typed prompting.\n"
        "WHY metrics: 'best found' alone is not a result. Three questions: did we find "
        "the best (regret), was the LLM good at its job (accuracy, differs per "
        "approach), was the search efficient (efficiency, invalid rate, diversity). One "
        "shared, unit-tested metrics module measures all three the same way."
    ),
)

# ======================= APPROACH 1 ======================================= #
section_slide("Approach 1", "LLM as Direct Optimizer")

content_slide(
    "A1: What and Why",
    [
        ("WHAT: the LLM is the inventor. Each round it sees tested molecules + ESOL "
         "LogS, proposes one new SMILES", 0, True),
        ("No math in the loop: the LLM both proposes and decides direction", 0, False),
        ("WHY: simplest possible LLM optimizer; if it has chemical intuition it shows "
         "here with nothing helping it", 0, False),
        ("HOW: build prompt -> paste -> validate SMILES (RDKit) -> reject mixtures -> "
         "ESOL score -> log -> repeat", 0, False),
        ("Three prompt variants to test how much wording matters:", 0, True),
        ("A Chain-of-thought: 'analyze features, then design'", 1, False),
        ("B Pragmatic: A + soft ban on trivial tricks", 1, False),
        ("C Constrained: hard limits (MW<150, polar group, <=1 ring, single molecule)",
         1, False),
        ("Key decision: show ESOL LogS in prompts (one consistent scoreboard)", 0, False),
    ],
    notes=(
        "WHY 2 runs here: Variant A run 2 switched models to prove the behavior is not "
        "one model's quirk; B and C run 2 tested reproducibility. That turned a single "
        "observation into a statement about reproducibility and path-dependence."
    ),
)

table_slide(
    "A1: per-run metrics (from analysis.py)",
    ["Variant.Run", "Best", "Improve", "Success", "Hit-rate", "Invalid", "Diversity"],
    [
        ["A.1", "+3.314", "+3.106", "0.75", "0.92", "0.00", "0.407"],
        ["A.2", "+2.184", "+1.976", "0.40", "1.00", "0.30", "0.284"],
        ["B.1", "+2.751", "+2.543", "0.27", "0.89", "0.18", "0.200"],
        ["B.2", "+0.563", "+0.355", "0.50", "0.83", "0.00", "0.186"],
        ["C.1", "+1.586", "+1.378", "0.40", "1.00", "0.00", "0.232"],
        ["C.2", "+1.258", "+1.050", "0.50", "0.90", "0.00", "0.243"],
    ],
    notes=(
        "HOW each metric is computed:\n"
        "Hit-rate = fraction of proposals whose ESOL beat the seed best (A1 makes no "
        "prediction, so this is its quality signal).\n"
        "Success rate = fraction of evals that set a new best.\n"
        "Invalid rate = 1 - mean(valid) from RDKit. Diversity = mean pairwise Tanimoto "
        "of Morgan fingerprints (lower = more diverse).\n"
        "WHY regret/normalized are N/A for A1: open-ended generation has no fixed pool, "
        "so no meaningful ceiling. The AqSolDB ESOL ceiling +17.14 is a degenerate "
        "unbounded value, not a real target.\n"
        "WHY these numbers: A wins on score but repeats one exploit (least diverse). "
        "B's two runs disagree (path-dependent). C is most reliable (0% invalid both)."
    ),
)

content_slide(
    "A1: headline finding -- the LLM exploits the oracle",
    [
        ("Unconstrained (Variant A), the LLM found ESOL has no chain-length penalty and "
         "no ceiling", 0, True),
        ("It added -CH(OH)- units forever (polyol chains), +0.28 LogS each, up to "
         "dodecitol +3.31 (chemically absurd)", 0, False),
        ("Replicated across Gemini, DeepSeek, ChatGPT -> a property of ESOL, not one "
         "model", 0, False),
        ("Each prompt closed one exploit, the LLM found the next:", 0, True),
        ("A chain -> B salt-mixture -> C (hard rules) forced real chemistry", 1, False),
        ("Takeaway: objective and constraint design matter as much as the LLM", 0, True),
    ],
    notes=(
        "The LLM does not cheat maliciously; it optimizes the objective exactly as "
        "written. This is the core weakness of a cheap descriptor oracle, and it is a "
        "good result to report. Note: word the absurd molecules as 'degenerate' or "
        "'exploited', honestly framed."
    ),
)

figure_slide(
    "A1 Figure: convergence.png",
    "convergence.png",
    [
        ("Best-so-far LogS vs iteration, 6 runs", 0, True),
        ("A (red/orange): climbs high via the unbounded polyol exploit", 1, False),
        ("B (blue/purple): runs DISAGREE, B1 late spike (salt), B2 honest plateau "
         "+0.56", 1, False),
        ("C (green/brown): smooth legit climbs, no spikes", 1, False),
        ("Take: unconstrained = exploit; soft ban = unreliable; hard rules = "
         "consistent", 0, True),
    ],
    notes="Dashed gray line at +0.21 is the seed best (starting point).",
)

figure_slide(
    "A1 Figures: behavior metrics",
    "invalid_rate.png",
    [
        ("invalid_rate.png (shown): A 15%, B 9.1% (path-dependent), C 0%", 0, True),
        ("Strict rules also make the LLM more reliable", 1, False),
        ("diversity.png: A least diverse (0.345, repeats the trick); B/C more "
         "diverse", 0, True),
        ("Removing the easy exploit forces exploration", 1, False),
        ("comparison.png: all 3 variants beat random (+0.41); the +17.14 ceiling is an "
         "ESOL illusion (use +2.14 on the slide)", 0, True),
    ],
    notes=(
        "comparison.png and diversity.png also exist in plots/. WHY 2 runs paid off: "
        "lets me state A's exploit is reproducible, B is path-dependent, C is reliable. "
        "None of that is possible from a single run."
    ),
)

# ======================= APPROACH 2 ======================================= #
section_slide("Approach 2", "BO with the LLM as a Regressor")

content_slide(
    "A2: What and Why",
    [
        ("WHAT: the LLM is a guesser. Fixed pool of 30 molecules; it predicts LogS (mu) "
         "+ confidence (1-10) for each", 0, True),
        ("The LLM does NOT choose what to test. An acquisition function does", 0, False),
        ("WHY: A1 showed the LLM can invent but exploit. A2 asks a narrower question: "
         "can it put a reliable number on solubility?", 0, False),
        ("HOW the loop:", 0, True),
        ("LLM predicts all 30 -> confidence mapped to uncertainty sigma", 1, False),
        ("EI or UCB scores each and picks ONE -> ESOL scores it -> repeat", 1, False),
        ("EI = expected gain over best + uncertainty bonus; UCB = mu + kappa*sigma",
         1, False),
        ("WHY EI and UCB: the two standard acquisition functions; everything else held "
         "fixed", 0, False),
        ("CRITICAL: the random pool's best was only +0.21; 1 of 30 beat the seed",
         0, True),
    ],
    notes=(
        "WHY 2 runs each: LLM predictions vary by model and session, so two runs per "
        "acquisition function check the result is not a single-session artifact. The "
        "pool was a random AqSolDB draw, mostly insoluble molecules, so the best score "
        "any method could reach was +0.21. Keep this in mind for every A2 figure."
    ),
)

table_slide(
    "A2: regression accuracy (from analysis2.py)",
    ["Metric", "Value", "Reading"],
    [
        ["MAE", "0.82", "Large miss on this scale"],
        ["RMSE", "1.13", "Big misses present"],
        ["Bias", "+0.73", "Guesses too HIGH (optimist)"],
        ["Pearson r", "+0.46", "Weak-moderate; some signal"],
        ["R squared", "-1.25", "WORSE than guessing the mean"],
        ["Sign acc vs seed", "0.78", "Direction usually right"],
        ["Confidence vs error", "-0.0007", "Confidence is meaningless"],
    ],
    notes=(
        "HOW: mu = LLM prediction, true = ESOL of the picked molecule. MAE=mean|mu-true|, "
        "RMSE=sqrt(mean(err^2)), bias=mean(mu-true), Pearson=corr, R2=1-SSres/SStot, "
        "sign-acc=fraction on correct side of the seed, confidence calibration = "
        "corr(confidence, |error|).\n"
        "WHY R^2 is negative: it compares the model's squared error to always guessing "
        "the average true value. The LLM is noisy AND biased upward, so it loses to that "
        "trivial baseline. Weak positive Pearson means it gets rough order partly right, "
        "but ordering is not enough for accurate numbers.\n"
        "WHY confidence is meaningless: the LLM gives a number because asked; it is not "
        "tied to real correctness (known calibration problem). So the sigma fed to EI/UCB "
        "carried almost no information."
    ),
    col_widths=[3.5, 2.0, 6.8],
    fs=14,
)

figure_slide(
    "A2 Figure: calibration2.png (key figure)",
    "calibration2.png",
    [
        ("LLM prediction mu vs true ESOL LogS; dashed = perfect", 0, True),
        ("Dots scatter widely, most ABOVE the line (+0.73 bias)", 1, False),
        ("Loose upward drift = weak +0.46 correlation", 1, False),
        ("Worst: predicted +2.5 for a true -0.28", 1, False),
        ("Take: off-the-shelf LLM is a weak, over-optimistic numeric predictor", 0, True),
    ],
    notes="This is the central honest finding of Approach 2.",
)

figure_slide(
    "A2 Figures: convergence and confidence",
    "convergence2.png",
    [
        ("convergence2.png (shown): y-axis spans only +0.208 to +0.210, a sliver", 0,
         True),
        ("All runs hit the pool ceiling in 3-4 iters, then flat (nothing better "
         "exists)", 1, False),
        ("confidence_error2.png: mean-error line is flat, corr -0.0007", 0, True),
        ("LLM never used confidence below 5, even when wrong", 1, False),
        ("comparison2.png: random +0.41 'beats' EI/UCB +0.21 ONLY because random draws "
         "from all 9,982; unfair", 0, True),
    ],
    notes=(
        "The right A2 comparison is EI/UCB vs the pool ceiling (+0.21), which both reach "
        "exactly. The bottleneck was the pool, not the math. This lesson shaped A3."
    ),
)

# ======================= APPROACH 3 ======================================= #
section_slide("Approach 3", "Preferential BO with the LLM as a Ranker")

content_slide(
    "A3: What and Why",
    [
        ("WHAT: the LLM never gives a number. It only judges duels: 'is A or B more "
         "soluble?'", 0, True),
        ("Many duels -> a ranking -> an acquisition picks the next molecule to ESOL-"
         "score", 0, False),
        ("WHY: A2 showed the LLM is a poor regressor, but LLMs compare better than they "
         "predict. Test that hypothesis", 0, False),
        ("HOW the loop:", 0, True),
        ("Select ~25 informative duels -> LLM answers A/B as JSON", 1, False),
        ("Bradley-Terry fit: P(i beats j)=sigmoid(u_i-u_j), gives utility + uncertainty",
         1, False),
        ("UCB on utility picks one -> ESOL scores it -> repeat", 1, False),
        ("Pool STRATIFIED by ESOL -> real ceiling +1.14 (vs A2's dead +0.21)", 0, True),
        ("Validated with an --auto ESOL oracle + 26 unit tests BEFORE any LLM run", 0,
         True),
    ],
    notes=(
        "WHY stratify by ESOL not experiment: the oracle is ESOL, which disagrees with "
        "experiment for salts/sugars, so an experiment-stratified pool was still dead. "
        "WHY validate first (anti-hallucination): --auto answers duels by true ESOL "
        "(optionally with noise) to prove the loop, the BT fit, the acquisition, and "
        "logging are correct without any LLM, and that it responds to ranker quality. "
        "Only then the real manual runs."
    ),
)

table_slide(
    "A3: ranking accuracy + outcome (from analysis3.py)",
    ["Run", "Best", "Regret", "Spearman", "Kendall", "Pairwise acc", "Top-1 hit",
     "NDCG@5"],
    [
        ["1", "+1.1375", "0.0", "+0.525", "+0.416", "0.708", "0", "0.703"],
        ["2", "+1.1375", "0.0", "+0.711", "+0.600", "0.800", "0", "0.856"],
    ],
    notes=(
        "HOW: pred = Bradley-Terry utility, true = ESOL of the whole pool. Spearman/"
        "Kendall = rank correlations; pairwise acc = fraction of molecule pairs ordered "
        "the same way; top-1 hit = is the utility's #1 the true best; NDCG@5 = top-5 "
        "ranking quality vs ideal.\n"
        "WHY good: 71-80% pairwise accuracy is far above random 50% and far better than "
        "A2's negative R^2. Ranking IS easier for the LLM than prediction (the core "
        "result).\n"
        "WHY top-1 hit = 0 yet ceiling reached: the BT #1 was not the single true best, "
        "but UCB also explores high-uncertainty candidates, so it tested the true best "
        "anyway within budget. A ranker can be imperfect at the very top and still drive "
        "a successful optimization.\n"
        "WHY regret genuinely 0 (unlike A2): the stratified pool had real headroom and "
        "the loop reached it."
    ),
    col_widths=[0.9, 1.6, 1.4, 1.8, 1.6, 2.2, 1.5, 1.3],
    fs=13,
)

figure_slide(
    "A3 Figure: ranking_quality3.png (headline)",
    "ranking_quality3.png",
    [
        ("Bradley-Terry utility vs true ESOL LogS, per run", 0, True),
        ("Points trend upward, tighter in run 2 (Spearman 0.71) than run 1 (0.53)", 1,
         False),
        ("Good but not perfect ranking, matches 0.71-0.80 pairwise accuracy", 1, False),
        ("Take: YES the LLM is a decent pairwise ranker, and better at ranking than at "
         "regression", 0, True),
    ],
    notes="This figure directly justifies the whole approach.",
)

figure_slide(
    "A3 Figure: convergence3.png",
    "convergence3.png",
    [
        ("Best-so-far vs iteration; real y-axis range now (stratified pool)", 0, True),
        ("Both runs climb from +0.21 seed and reach the +1.14 ceiling", 1, False),
        ("Gain happens in a few jumps (hence low success-rate)", 1, False),
        ("Take: with a proper pool, the PBO loop genuinely optimizes within budget", 0,
         True),
        ("Validation: --auto perfect ranker reaches ceiling fast; 40% noise degrades to "
         "Spearman ~0.59", 0, True),
    ],
    notes=(
        "comparison3.png also exists: both runs reach the pool ceiling above the seed. "
        "The --auto validation shows convergence is caused by ranking quality, not a bug "
        "or a lucky pool."
    ),
)

# ======================= OBSERVATIONS ===================================== #
section_slide("Wrap-up", "Observations and Conclusions")

table_slide(
    "Cross-approach comparison (compare_approaches.py)",
    ["Approach", "Best (mean/max)", "Improve", "Success", "LLM quality (own metric)"],
    [
        ["A1 direct", "1.94 / 3.31", "+1.73", "0.47", "hit-rate 0.92"],
        ["A2 regressor", "0.21 / 0.21", "+0.00", "0.10",
         "MAE 0.82, R2 -1.30, sign 0.78"],
        ["A3 ranker", "1.14 / 1.14", "+0.93", "0.10",
         "pairwise 0.75, Spearman +0.62, NDCG 0.78"],
    ],
    notes=(
        "CAVEAT (a required slide): the three are NOT on identical problems. A1 is "
        "open-ended (no pool, regret undefined); A2 and A3 use different pools (A2 "
        "ceiling +0.21, A3 +1.14). Compare best-LogS and efficiency; use each "
        "approach's own quality metric for LLM skill. Figure comparison_all.png shows "
        "the best-LogS bars with the random baseline."
    ),
    col_widths=[2.3, 2.6, 1.5, 1.4, 4.5],
    fs=13,
)

content_slide(
    "Three big findings",
    [
        ("1. A cheap descriptor oracle is exploitable (A1)", 0, True),
        ("The LLM optimizes ESOL exactly as written until hard constraints force real "
         "chemistry", 1, False),
        ("2. The LLM is a poor regressor but a decent ranker (A2 vs A3)", 0, True),
        ("Regressor: R^2 negative, confidence meaningless. Ranker: 71-80% pairwise "
         "correct", 1, False),
        ("This is the central result: comparison is the strength, exact prediction the "
         "weakness", 1, False),
        ("3. Search-space design is the real bottleneck (A2 vs A3)", 0, True),
        ("Same loop: a failure on a dead pool (A2), a success on a stratified pool "
         "(A3)", 1, False),
        ("Plus: one shared, unit-tested metrics module -> every number is validated, "
         "none hallucinated", 0, True),
    ],
    notes=(
        "WHY the metrics framework is itself a contribution: shared optimization metrics "
        "are comparable across approaches; per-approach accuracy judges each LLM role by "
        "the metric that fits it. Every reported number has a known-answer test behind "
        "it (26 tests total)."
    ),
)

content_slide(
    "Future work",
    [
        ("Fix the oracle's exploitability: cap LogS / penalize MW, or use a stronger "
         "solubility predictor", 0, True),
        ("Fix A2's pool: re-run on an ESOL-stratified pool (proven in A3) for a fair "
         "EI-vs-UCB fight", 0, True),
        ("More runs: with API access, 5-10 seeds per setting + confidence intervals",
         0, True),
        ("Better uncertainty: numeric range, multi-sample spread, or Bradley-Terry "
         "std_err instead of self-reported confidence", 0, True),
        ("Combine approaches: LLM proposes candidates (A1) -> rank by duels (A3) -> "
         "evaluate. Use the LLM where it is strong", 0, True),
        ("Fine-tuning on solubility data; scale A3 duels (more duels -> tighter "
         "ranking, likely raises top-1 hit)", 0, True),
    ],
    notes=(
        "The natural synthesis combines the LLM's strengths (invention and comparison) "
        "and avoids its weakness (exact numeric prediction). Every result here used "
        "off-the-shelf models with no fine-tuning."
    ),
)

title_slide(
    "Thank you",
    "Questions?",
    "Anand Karna  |  Code, figures and per-run metric CSVs all reproducible from the repo",
)

prs.save(OUT)
print(f"Saved {len(prs.slides.__iter__.__self__._sldIdLst)} slides to {OUT}")
